version: '3'
services:
  app:
    container_name: app
    build: 
      context: .
    ports:
      - 8080:8080
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    expose:
      - 5432
    hostname: db
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_PASSWORD
      - POSTGRES_DB=process.env.POSTGRES_DB
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 9000:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=process.env.PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=process.env.PGADMIN_DEFAULT_PASSWORD
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - db
    volumes:
       - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    
  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes: 
      - ./zoo/data:/var/lib/zookeeper/data
      - ./zoo/log:/var/lib/zookeeper/log
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
  kafka:
    image: 'confluentinc/cp-kafka:latest'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_LISTENERS=INTERNAL://:9092, OUTSIDE://:9094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://:9092, OUTSIDE://:9094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT

    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    
    depends_on:
      - zookeeper
    
    volumes: 
      - ./kafka/data:/var/lib/kafka/data
    

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    command: >
      bash -c 
        "sleep 5s &&
        kafka-topics --create --topic=user --if-not-exists --bootstrap-server kafka:9092"
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  control-center:
    image: confluentinc/cp-enterprise-control-center:6.0.1
    hostname: control-center
    depends_on:
      - kafka
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      PORT: 9021
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
volumes:
    pgadmin: