version: '3'
services:
  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
   
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    container_name: db
    tty: true
    volumes:
      - .pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=process.env.POSTGRES_USER
      - POSTGRES_PASSWORD=process.env.POSTGRES_PASSWORD
      - POSTGRES_DB=process.env.POSTGRES_DB

    depends_on:
      - app
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - 9000:80
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=process.env.PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD=process.env.PGADMIN_DEFAULT_PASSWORD
      
    depends_on:
      - db
    volumes:
       - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

volumes:
    pgadmin: