name: nexar_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  postgres: ^2.4.6
  shelf: ^1.1.0
  shelf_router: ^1.1.3

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0

scripts:
  dev: dart run bin/server.dart